/* errortxt.c  (c) Markus Hoffmann   */

/* This file is part of X11BASIC, the basic interpreter for Unix/X
 * ============================================================
 * X11BASIC is free software and comes with NO WARRANTY - read the file
 * COPYING for details
 */

static char *errortxt[] = { 
/*   0*/  "Division durch Null",
/*   1*/  "Ueberlauf",
/*   2*/  "Zahl nicht Integer -2147483648 .. 2147483647",
/*   3*/  "Zahl nicht Byte 0 .. 255",
/*   4*/  "Zahl nicht Wort -32768 .. 32767",
/*   5*/  "Quadratwurzel nur für positive Zahlen",
/*   6*/  "Logarithmen nur für Zahlen größer Null",
/*   7*/  "Unbekannter Fehler",
/*   8*/  "Speicher voll",
/*   9*/  "Funktion oder Befehl noch nicht möglich %s",
/*  10*/  "String zu lang max. 32767 Zeichen",
/*  11*/  "Fehler #11",
/*  12*/  "Programm zu lang Speicher voll NEW",
/*  13*/  "Fehler #13",
/*  14*/  "Feld %s zweimal dimensioniert",
/*  15*/  "Feld nicht dimensioniert: %s()",
/*  16*/  "Feldindex zu groß",
/*  17*/  "Dim zu groß",
/*  18*/  "Falsche Anzahl Indizes",
/*  19*/  "Procedure %s nicht gefunden",
/*  20*/  "Label %s nicht gefunden",
/*  21*/  "Bei Open nur erlaubt: \"I\"nput  \"O\"utput \"A\"ppend \"U\"pdate",
/*  22*/  "File schon geöffnet",
/*  23*/  "File # falsch",
/*  24*/  "File nicht geöffnet",
/*  25*/  "Falsche Eingabe, keine Zahl",
/*  26*/  "Fileende erreicht EOF",
/*  27*/  "Zu viele Punkte für Polyline/Polyfill maximal 128",
/*  28*/  "Feld muss eindimensional sein",
/*  29*/  "Fehler #29",
/*  30*/  "Merge - Kein ASCII-File",
/*  31*/  "Merge - Zeile zu lang - Abbruch",
/*  32*/  "==> Syntax nicht korrekt",
/*  33*/  "Marke nicht definiert",
/*  34*/  "Zu wenig Data",
/*  35*/  "Data nicht numerisch",
/*  36*/  "Programmstruktur Fehlerhaft %s",
/*  37*/  "Diskette voll",
/*  38*/  "Befehl im Direktmodus nicht möglich",
/*  39*/  "Programmfehler Kein Gosub möglich",
/*  40*/  "Clear nicht möglich in For-Next-Schleifen oder Proceduren",
/*  41*/  "Cont nicht möglich",
/*  42*/  "Zu wenig Parameter",
/*  43*/  "Ausdruck zu komplex",
/*  44*/  "Funktion %s nicht definiert",
/*  45*/  "Zu viele Parameter",
/* .*/  "Parameter falsch keine Zahl",
/* /*/  "Parameter falsch kein String",
/* 0*/  "Open \"R\" - Satzlänge falsch",
/* 1*/  "Zu viele \"R\"-Files (max. 31)",
/* 2*/  "Kein \"R\"-File",
/* 3*/  "Parser: Syntax Error <%s>",
/* 4*/  "Fields größer als Satzlänge",
/* 5*/  "Unbekannter Fehler 53",
/* 6*/  "GET/PUT Field-String Länge falsch",
/* 7*/  "GET/PUT Satznummer falsch",
/* 8*/  "Zu wenig Parameter",
/* 57*/  "Variable %s noch nicht initialisiert",
/* 58*/  "Variable %s ist vom falschen Typ",
/* 59*/  "Unbekannter Fehler 59",
/* <*/  "Sprite-String-Länge falsch",
/* =*/  "Fehler bei RESERVE",
/* >*/  "Menu falsch",
/* ?*/  "Reserve falsch",
/* @*/  "Pointer falsch",
/* A*/  "Feldgröße < 256",
/* B*/  "Kein VAR-Array",
/* C*/  "ASIN/ACOS falsch",
/*  68*/  "Falsche VAR-Type",
/*  69*/  "ENDFUNC ohne RETURN",
/*  70*/  "Unbekannter Fehler 70",
/*  71*/  "Index zu groß",
/* H*/  "Unbekannter Fehler 72",
/* I*/  "Unbekannter Fehler 73",
/* J*/  "Unbekannter Fehler 74",
/* K*/  "Unbekannter Fehler 75",
/* L*/  "Unbekannter Fehler 76",
/* M*/  "Unbekannter Fehler 77",
/* N*/  "Unbekannter Fehler 78",
/* O*/  "Unbekannter Fehler 79",
/* P*/  "Matrizenoperationen nur für ein- oder zweidimensionale Felder",
/* Q*/  "Matrizen haben nicht die gleiche Ordnung",
/* R*/  "Vektorprodukt nicht definiert",
/* S*/  "Matrizenprodukt nicht definiert",
/* T*/  "Scalarprodukt nicht definiert",
/* U*/  "Transposition nur für zweidimensionale Matrizen",
/* V*/  "Matrix nicht quadratisch",
/* W*/  "Transposition nicht definiert",
/* X*/  "FACT/COMBIN/VARIAT nicht definiert",
/*  89*/  "Unbekannter Fehler 89",
/*  90*/  "Fehler bei Local",
/*  91*/  "Fehler bei For",
/*  92*/  "Resume (next) nicht möglich   Fatal, For oder Local",
/*  93*/  "Stapel-Fehler",
/*  94*/  "Unbekannter Fehler 94",
/* _*/  "Unbekannter Fehler 95",
/* `*/  "Unbekannter Fehler 96",
/* a*/  "Unbekannter Fehler 97",
/* b*/  "Unbekannter Fehler 98",
/* c*/  "Unbekannter Fehler 99",
/* d*/  "X11BASIC Version 1.50  Copyright 1998 Markus Hoffmann",
/* e*/  "Unbekannter Fehler 101",
/* f*/  "2 Bomben - Bus Error Peek/Poke falsch?",
/* g*/  "3 Bomben - Adress error Ungerade Wort-Adresse! Dpoke/Dpeek, Lpoke/Lpeek?",
/* h*/  "4 Bomben - Illegal Instruction ungltiger Maschinenbefehl",
/* i*/  "5 Bomben - Divide by Zero 68000 Division durch Null",
/* j*/  "6 Bomben - CHK-Exeption 68000 CHK-Befehl",
/* k*/  "7 Bomben - TRAPV-Exeption 68000 TRAPV-Befehl",
/* l*/  "8 Bomben - Privilege Violation 68000 Privilegverletzung",
/* m*/  "9 Bomben - Trace Exeption 68000 Trace ohne Monitor",
/* n*/  "Unbekannter Fehler 110",
/* o*/  "Unbekannter Fehler 111",
/* p*/  "Unbekannter Fehler 112",
/* q*/  "Unbekannter Fehler 113",
/* r*/  "Unbekannter Fehler 114",
/* s*/  "Unbekannter Fehler 115",
/* t*/  "Unbekannter Fehler 116",
/* u*/  "Unbekannter Fehler 117",
/* v*/  "Unbekannter Fehler 118",
/* w*/  "Unbekannter Fehler 119",
/* x*/  "Unbekannter Fehler 120",
/* y*/  "Unbekannter Fehler 121",
/* z*/  "Unbekannter Fehler 122",
/* {*/  "Unbekannter Fehler 123",
/*  */  "Unbekannter Fehler 124",
/* }*/  "Unbekannter Fehler 125",
/* ~*/  "Unbekannter Fehler 126",
/* 127*/  "Unbekannter Fehler 127",
/* €*/  "Unbekannter Fehler -128",
/* */  "Unbekannter Fehler -127",
/* ‚*/  "Unbekannter Fehler -126",
/* ƒ*/  "Unbekannter Fehler -125",
/* „*/  "Unbekannter Fehler -124",
/* …*/  "Unbekannter Fehler -123",
/* †*/  "Unbekannter Fehler -122",
/* ‡*/  "Unbekannter Fehler -121",
/* ˆ*/  "Unbekannter Fehler -120",
/* ‰*/  "Unbekannter Fehler -119",
/* Š*/  "Unbekannter Fehler -118",
/* ‹*/  "Unbekannter Fehler -117",
/* Œ*/  "Unbekannter Fehler -116",
/* */  "Unbekannter Fehler -115",
/* Ž*/  "Unbekannter Fehler -114",
/* */  "Unbekannter Fehler -113",
/* */  "Unbekannter Fehler -112",
/* ‘*/  "Unbekannter Fehler -111",
/* ’*/  "Unbekannter Fehler -110",
/* “*/  "Unbekannter Fehler -109",
/* ”*/  "Unbekannter Fehler -108",
/* •*/  "Unbekannter Fehler -107",
/* –*/  "Unbekannter Fehler -106",
/* —*/  "Unbekannter Fehler -105",
/* ˜*/  "Unbekannter Fehler -104",
/* ™*/  "Unbekannter Fehler -103",
/* š*/  "Unbekannter Fehler -102",
/* ›*/  "Unbekannter Fehler -101",
/* œ*/  "Unbekannter Fehler -100",
/* */  "Unbekannter Fehler -099",
/* ž*/  "Unbekannter Fehler -098",
/* Ÿ*/  "Unbekannter Fehler -097",
/*  */  "Unbekannter Fehler -096",
/* ¡*/  "Unbekannter Fehler -095",
/* ¢*/  "Unbekannter Fehler -094",
/* £*/  "Unbekannter Fehler -093",
/* ¤*/  "Unbekannter Fehler -092",
/* ¥*/  "Unbekannter Fehler -091",
/* ¦*/  "Unbekannter Fehler -090",
/* §*/  "Unbekannter Fehler -089",
/* ¨*/  "Unbekannter Fehler -088",
/* ©*/  "Unbekannter Fehler -087",
/* ª*/  "Unbekannter Fehler -086",
/* «*/  "Unbekannter Fehler -085",
/* ¬*/  "Unbekannter Fehler -084",
/* ­*/  "Unbekannter Fehler -083",
/* ®*/  "Unbekannter Fehler -082",
/* ¯*/  "Unbekannter Fehler -081",
/* °*/  "Unbekannter Fehler -080",
/* ±*/  "Unbekannter Fehler -079",
/* ²*/  "Unbekannter Fehler -078",
/* ³*/  "Unbekannter Fehler -077",
/* ´*/  "Unbekannter Fehler -076",
/* µ*/  "Unbekannter Fehler -075",
/* ¶*/  "Unbekannter Fehler -074",
/* ·*/  "Unbekannter Fehler -073",
/* ¸*/  "Unbekannter Fehler -072",
/* ¹*/  "Unbekannter Fehler -071",
/* º*/  "Unbekannter Fehler -070",
/* »*/  "Unbekannter Fehler -069",
/* ¼*/  "Unbekannter Fehler -068",
/* ½*/  "* Speicherblockfehler",
/* ¾*/  "* Kein Binärprogramm",
/* ¿*/  "* Interner GEMDOS-Fehler",
/* À*/  "* GEMDOS-Bereichsfehler Seek falsch?",
/* Á*/  "Unbekannter Fehler -63",
/* Â*/  "Unbekannter Fehler -62",
/* Ã*/  "Unbekannter Fehler -61",
/* Ä*/  "Unbekannter Fehler -60",
/* Å*/  "Unbekannter Fehler -59",
/* Æ*/  "Unbekannter Fehler -58",
/* Ç*/  "Unbekannter Fehler -57",
/* È*/  "Unbekannter Fehler -56",
/* É*/  "Unbekannter Fehler -55",
/* Ê*/  "Unbekannter Fehler -54",
/* Ë*/  "Unbekannter Fehler -53",
/* Ì*/  "Unbekannter Fehler -52",
/* Í*/  "Unbekannter Fehler -51",
/* -50*/  "* Verbindung wurde unterbrochen",
/* -49*/  "* Keine weiteren Dateien",
/* -48*/  "* Verbindungsaufbau verweigert",
/* -47*/  "* File/Verbindung schon geoeffnet",
/* -46*/  "* Ungültige Laufwerksbezeichnung",
/* -45*/  "* keine Verbindung, Verbindung unterbrochen ?",
/* -44*/  "* Besetzt, Verbindung nicht möglich",
/* -43*/  "* Verbindungsaufbau nicht möglich",
/* -42*/  "Error bei shared memory: %s",
/* -41*/  "Message Fehler: %s",
/* -40*/  "* Ungültige Speicherblockadresse",
/* -39*/  "* Speicher voll",
/* -38*/  "* Fehler -38",
/* -37*/  "* Ungültiges Handle",
/* -36*/  "* Zugriff nicht möglich",
/* -35*/  "* Zu viele Dateien offen",
/* -34*/  "* Pfadname nicht gefunden",
/* -33*/  "* Datei nicht gefunden",
/* -32*/  "* Operation auf diesem Kanal nicht möglich",
/* -31*/  "* Zu viele Links",
/* -30*/  "* Read-Only File-System",
/* -29*/  "* Seek falsch",
/* -28*/  "* File-System ist voll",
/* -27*/  "* File too large",
/* -26*/  "* Text file busy",
/* -25*/  "* Not a typewriter",
/* -24*/  "* Too many open files",
/* -23*/  "* File table overflow",
/* -22*/  "* Invalid argument",
/* -21*/  "* Is a directory",
/* -20*/  "* Not a directory",
/* -19*/  "* No such device",
/* -18*/  "* Cross-device link",
/* -17*/  "* Andere Diskette einlegen",
/* -16*/  "* Bad Sektor (Verify)",
/* -15*/  "* Unbekanntes Gerät",
/* -14*/  "* Diskette wurde gewechselt",
/* -13*/  "* File ist zu gross für diese Operation",
/* -12*/  "* Zur Zeit sind keine weiteren offenen Files möglich",
/* -11*/  "* Lesefehler",
/* -10*/  "* Schreibfehler",
/*  -9*/  "* Kein Papier",
/*  -8*/  "* Sektor nicht gefunden",
/*  -7*/  "* Unknown Media Boot-Sector falsch",
/*  -6*/  "* Seek Error Spur nicht gefunden",
/*  -5*/  "* Bad Request Ungültiger Befehl",
/*  -4*/  "* CRC Fehler Disk-Prüfsumme falsch",
/*  -3*/  "* Unbekannter Befehl",
/*  -2*/  "* Zeitüberschreitung",
/*  -1*/  "* Allgemeiner IO-Fehler %s"
};

static char errbuffer[256];
char *error_text(unsigned char err, char *bem) {
        
	
	sprintf(errbuffer,errortxt[err],bem );
	return( errbuffer );
}

