# Dockerfile for X11-Basic based on the one by Bruno https://github.com/shakenfr/x11basic_docker/
# Start with Ubuntu 20.04
# The docker file generates an installable .deb package of X11-Basic as well as 
# the User-Manul as .pdf
# as well as a setup.exe for WINDOWS
#
FROM ubuntu:20.04
VOLUME work
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

#
# Basic Packages
#


RUN apt-get update \
&& apt-get install -y apt-utils git tcsh nano vim curl wget make gcc build-essential
RUN apt-get install -y  checkinstall imagemagick transfig zip unzip
RUN apt-get install -y libreadline-dev xorg-dev libasound2-dev fftw-dev libjpeg-dev \ 
&& apt-get install -y libblas-dev libgmp-dev liblapack-dev libusb-dev libbluetooth-dev libfreetype6-dev
#
# Crosscompiler for WINDOWS
#
RUN apt-get install -y gcc-mingw-w64 wine
#
# Latex Installation for the manual
#
RUN apt-get install -y texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-fonts-extra
#
# Some more tex packages
#
RUN apt-get install -y texlive-xetex texlive-pstricks texlive-science texlive-formats-extra
#
# Crosscompiler for version for ATARI ST TOS
#
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:vriviere/ppa
RUN apt install -y cross-mint-essential

#
# prepare ImageMagic (for Ubuntu)
#
RUN cd /etc/ImageMagick-6/;sed -i 's/"none"/"read | write"/g' policy.xml
#
# Prepare for the WINDOWS version
#
RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y wine32

#
# Clean up some bit
#
RUN apt-get clean


RUN wget https://files.jrsoftware.org/is/5/isetup-5.5.8.exe  
RUN mkdir -p /root
COPY wineblob.tar.gz /root/
RUN cd /root/; tar xzfv wineblob.tar.gz
RUN chown -R 0 /root/.wine
#RUN wine isetup-5.5.8.exe

# For some reason this command is needed to initialize wine and its directory
RUN wine cmd /c 'echo %PROGRAMFILES%'

#
# Get and make X11-Basic
#
RUN echo "Get and make X11-Basic"
RUN git clone https://codeberg.org/kollo/X11Basic.git
RUN mkdir -p X11Basic/src/Debian/Outputs
RUN cd X11Basic/src/;./configure --prefix=/usr
RUN cd X11Basic/src/;sed -i 's/..\/examples\/compiler\/ybasic/\/X11Basic\/examples\/compiler\/ybasic/g' Makefile
RUN cd X11Basic/src;make;make install
#
# Make the User-Manual
#
RUN mkdir -p X11Basic/doc/manual/Outputs
# corrected upstream
RUN cd X11Basic/doc/manual/tex/;sed -i 's/usepackage{tikz}/usepackage{tikz}\\usepackage{etex}/g' main.tex
RUN cd X11Basic/doc/manual/;make
RUN cp -R X11Basic/doc/manual/Outputs/X11-Basic-manual-*.pdf /
#
# Make the debian package
#
RUN cd X11Basic/src/;sed -i 's/sudo\ checkinstall/checkinstall/g' Makefile; cat Makefile
RUN cd X11Basic/src/;sed -i 's/libreadline7/libreadline8/g' Makefile; cat Makefile
# Now make the debian package
RUN cd X11Basic/src;make static
RUN cd X11Basic/src;make deb
# copy the results in the root of the container
RUN cp -R /X11Basic/src/Debian/Outputs/*.deb /
#RUN cp -R /X11Basic/* /

#
# Make the version for ATARI ST TOS
#
RUN cd X11Basic/src;make clean;make tos
RUN cp -R /X11Basic/src/*.zip /

#
# Make Version for WINDOWS
#
RUN cd X11Basic/src;make windows
RUN cp -R X11Basic/src/Inno-Output/*.exe /



# Make MQTT Version (TODO)
##############################
#
# get the paho.c library
#

RUN git clone https://github.com/eclipse/paho.mqtt.c.git
RUN cd paho.mqtt.c;git checkout fbf9828200f46e212189d98eaedf8e11281e409a
# get MQTT-hyperdash
#RUN git clone https://codeberg.org/kollo/MQTT-Hyperdash.git

#RUN cp MQTT-Hyperdash/etc/paho-description-pak paho.mqtt.c/description-pak
#RUN cp MQTT-Hyperdash/etc/paho-Makefile paho.mqtt.c/Makefile
#RUN cd paho.mqtt.c/;sed -i 's/sudo\ checkinstall/checkinstall/g' Makefile
#RUN cd paho.mqtt.c/;sed -i 's/sudo\ chown/chown/g' Makefile
#RUN cd paho.mqtt.c;make;make deb

# more TBD
# TODO


WORKDIR /work
CMD ["/bin/sh"]
