.TH X11BASIC 1 21-Dec-2012 "Version 1.21" "Basic Interpreter"
.SH NAME
xbasic (X11-Basic) \- The BASIC language interpreter and shell
.SH SYNOPSIS
.B xbasic
[\--eval <expression>] [-e <command>] [-l] [<filename>]

.SH DESCRIPTION

X11-Basic is a dialect of the BASIC programming language with graphics
capability that integrates features like shell scripting, cgi-Programming and 
full graphical visualisation into the easy to learn basic language on modern 
computers.

The syntax is most similar to the old GFA-Basic ATARI ST
implementation. Old GFA-programs should run with only few changes. Also 
DOS/QBASIC programmers will feel comfortable.

Ancient ANSI-Basic programs (with line numbers) can be converted to X11-Basic 
with the 
.I bas2x11basic 
program (see the man page 
.I bas2x11basic(1)
).

.IR xbasic 
is the script interpreter. It interpretes basic command-files (programs), which 
usually have the extension .bas or .xbas.
It can also run in interactive mode in which case it interpretes single lines of
code, which are entered.

.SH COMMANDLINE OPTIONS
.P
.SS \ <file>
load and run script <file>
.br
.SS \-l <file>
only load script, do not execute
.br
.SS \--eval <expression>
evaluate expression
.br
.SS \-e <command>
execute command
.br
.SS \-version
shows version, program and other information and exits
.SS -h --help
print a short help
.SS --help <topic>
print help on topic
.SS --daemon
daemon mode

For detailed help and description of the implemented basic commands take a 
look at the README file which comes with the X11Basic package. There is also a 
full users manual available as *.pdf file on the homepage.

.SH INTERACTIVE USE
If no options are given on the command line, 
.B xbasic
will run interactivly.

A prompt will be displayed and any command can be typed in. It will be
excecuted immediately after pressing return or enter. The input is buffered 
and can be edited using the up and down arrows on the keyboard.
 
.B To quit the program
simply enter 
.IR quit
or press 
.IR CTRL-C.

.SH EXAMPLES
.nf
xbasic testme.bas
xbasic -e 'alert 1,"Hello world !",1," OK ",b'
xbasic --eval 1+3-4*3
xbasic --help "*nl*"
.fi

You can find many sample programs in 
.I /usr/share/doc/packages/X11Basic/examples.

.SH X11-Basic as daemon:
The commandline option --daemon forces the interpreter to run in daemon-mode 
(with no terminal connected).
No prompt is given and the input is not echoed back. 

.SH X11-Basic as shell:
X11-Basic programs can be excecuted like shell scripts.
If the xbasic interpreter was installed in 
.I /bin/ 
any X11-Basic program with
.nf
 #!/bin/xbasic
.fi
in the first command line can be excecuted directly.


.SH The X11-Basic Language


For a complete language reference of X11-Basic please refer to the manual.
You should be able to find one at
.I http://x11-basic.sourceforge.net/x11basic.html


.SH VERSION
This page was created for V.1.21
.SH BUG REPORTS

If you find a bug in the X11-Basic interpreter, you should
report it. But first, you should make sure that it really is
a bug, and that it appears in the latest version of the
X11-Basic package that you have.

Once you have determined that a bug actually exists, mail a
bug report to kollo@users.sourceforge.net. If you have a fix,
you are welcome to mail that as well! Suggestions may 
be mailed to the X11-Basic mailing list on 
www.sourceforge.net/projects/x11-basic  or posted to the bug
tracking system.

Comments and  bug  reports  concerning  this  manual  page
should be directed to kollo@users.sourceforge.net.
.SH BUGS
There are probably still some bugs
.SH AUTHOR
Markus Hoffmann <kollo@users.sourceforge.net>
.SH COPYRIGHT
Copyright (C) 1997-2013 Markus Hoffmann <kollo@users.sourceforge.net>

This program is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. See the GNU General Public License for more
details.
.SH SEE ALSO

http://x11-basic.sourceforge.net/

/usr/share/doc/x11basic/

tcsh(1), sh(1), readline(3), xbc(1), bas211basic(1)
