.TH X11BASIC 1 19-Sep-2000 LOCAL "Linux User Tools"
.SH NAME
xbasic \- Basic shell
.SH SYNOPSIS
.B xbasic
[--eval <Ausdruck>] [-e <kommando>] [-l] [<filename>]

.SH DESCRIPTION
This program is a frontend for every cdripper and mp3-encoder program. It
uses CDDB-functionality for converting audio-cds to mp3.
It can run in interactive and batch-mode.

.SH OPTIONS
.P
.I \ <file>
load and rund script <file>
.P
.I \-l <file>
only load script do not execute
.P
.I \--eval <expression>
evaluate expression
.P
.I \-e <command>
execute command
.P
.I \-version
shows version, program and other informations and exits

.PP
For detailed help take a look in the README file. Handling of interactive-
mode should be obviously.
.PP

.RE
.SH INTERACTIVE USE
If no options are given on the command line, 
.B xbasic
will run interactivly.


quit program

.SH EXAMPLES

xbasic testme.bas

xbasic -e 'alert 1,"Hallo !",1," OK ",b'

xbasic --eval 1+3-4*3

.SH X11-Basic als Daemon:

wird X11-Basic mit
xbasic --daemon
gestartet, so erscheint bei der Kommandoeingabe kein Prompt und es erfolgt kein 
Echo der Tastatureingabe.

.SH X11-Basic als Shell:

X11-Basic Programme koennen auch wie Shell-Scripts gestartet werden.
Hierzu installiert man xbasic in /bin/. Mit der Anweisung
#!/bin/xbasic
in der ersten Zeile des Scipts wird es als X11-Basic-Programm ausgefuehrt.



.SH VERSION
Page was created for V1.01
.SH BUGS
Still some bugs


.SH MAINTAINER 
Markus Hoffmann <m.hoffmann@uni-bonn.de>

.SH SEE ALSO

tcsh(1)
