.TH XBBC 1 04-Jan-2019 "Version 1.27" "X11-Basic"
.SH NAME
xbbc \- X11-Basic bytecode compiler 
.SH SYNOPSIS
.B xbbc
.RI "[ " option " ] " 
[\fB\-o\fR \fIoutfile\fR]
.IR <filename>

.SH DESCRIPTION

X11-Basic is a dialect of the BASIC programming language with graphics.

.B xbbc
can be used to make bytecode-binaries out of *.bas script files. These bytecode 
files can be interpreted by the X11-Basic virtual machine (\fIxbvm(1)\fR) 
and they run about 10-20 times faster than the interpreted .bas files. Since 
.B xbbc
is a real compiler, some restrictions to the code apply. (Not every X11-Basic 
program which does well on the interpreter can be correctly compiled),
.PP
For a desciption of the X11-Basic language and usage of the interpreter see
.I xbasic(1)\fR.

.SH Filenames

.B xbbc 
processes one input file. The suffix of the input file is usually .bas.
The default output file name is 
.I b.b
but you can specify alternate names with the -o option.

.SH OPTIONS
.TP
.BR \-o " \fIfile\fR
Place output in file 
.I file
\&. 
If you do not specify `\|\c
.B \-o\c
\&\|', the default is to produce a file `\|\c
.B b.b\c
\.
.TP
.BR \-\-version
shows version, program and other information and exits
.TP
.BR \-h ", " \-\-help
print a short help.

For detailed help and a description of the implemented basic commands take a look
at the README file which ships with the X11-Basic package.


.SH EXAMPLES
.nf
xbbc testme.bas
 produces a bytecode file b.b
xbbc testme.bas -o testme.b 
 produces a bytecode file testme.b
.fi

.SH The bytecode compiler

.B xbbc 
is a compiler. It compiles the BASIC source code into a bytecode of a
virtual stack machine. This virtual stack machine needs to be emulated on each
different operating system platform, but the bytecode itself is still portable.
The bytecode is very compact and similar to machine code, but still it is
independant of the actual processor hardware. With an additional small step it
can be compiled to native assembler or machine code. (For linux this is done by
the 
.I xb2c(1) 
translator and 
.I gcc(1)
, for other operating systems such a translator has not yet been created).

There is no way to recreate the source code from the bytecode. 

.SH VERSION
Page was created for V.1.18

.SH BUG REPORTS  

If you find a bug in the X11-Basic bytecode compiler, you should report it. But
first, you should make sure that it really is a bug, and that it appears in the
latest version of the X11-Basic package that you have.

Once you have determined that a bug actually exists, mail a bug report to
kollo@users.sourceforge.net. If you have a fix, you are welcome to mail that as
well! Suggestions may be mailed to the x11-basic bug tracking system.

Comments and bug reports concerning this manual page should be directed to
kollo@users.sourceforge.net.

.SH AUTHOR
Markus Hoffmann <kollo@users.sourceforge.net>

.SH COPYRIGHT
Copyright (C) 1997-2019 Markus Hoffmann <kollo@users.sourceforge.net>

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

.SH SEE ALSO
xbasic(1), xbvm(1), xbc(1), xb2c(1)
