
/* Example Program how to link X11-Basic Object codes (produced by xbc)
   with your c-Program                        (c) Markus Hoffmann 2004   */

/* Example Program how to use the x11basic-Library
   with your c-Program                        (c) Markus Hoffmann 2004   */


/* You will have to compile this (testme.c)

gcc -fomit-frame-pointer -o testme -L/usr/X11R6/lib -lx11basic -ldl -lm 
    -lreadline -lncurses -lX11 testme.c anyroutine.o

*/

#include <stdlib.h>
#include <stdio.h>

/* X11-Basic needs these declarations:  */

extern void reset_input_mode(),x11basicStartup();
extern int param_anzahl;
extern char **param_argumente;
int programbufferlen=0;
char ifilename[]="dummy";
char *programbuffer=NULL;
const char version[]="dummy";
const char vdate[]="dummy";
char *program[]={};
int prglen=sizeof(program)/sizeof(char *);


/* This is the entrace routine procedure produced by xbc  */

extern double enter_0001();

/* This is for single command execution: */

extern void kommando(char *);


/* Here your program starts */

main(int anzahl, char *argumente[]) {
  double ret;
  /* Initialize the x11basic-library */
  x11basicStartup(); set_input_mode(1,0);
  atexit(reset_input_mode);
  param_anzahl=anzahl;
  param_argumente=argumente;

  /* Here your code can follow */

  /* ... */
 
  /* ... */
  
  /* If you like, you can use single x11basic-commands: */

  kommando("PBOX 10,10,100,100");
  kommando("SHOWPAGE");
  kommando("KEYEVENT");
  /* ... */

  /* This is how you can execute a X11-Basic Function generated by xbc. 
  The Parameters have to be convertet into the string */
  ret=enter_0001("TEST(1,2,3)");


}
