Ubuntu 16.04:

general:

sudo apt-get install autoconf xorg-dev libgcrypt20-dev libgmp-dev \
libasound2-dev liblapack-dev libreadline-dev libusb-dev fftw2


Fur building the WINDOWS version:
sudo apt-get install gcc-mingw-w64 wine iscc innosetup-qsp-5.5.9.exe


Building the manual and doc-files:

sudo apt-get install asciidoctor <latex>


For the Android Version:

sudo apt-get install gradle
