
/* Example Program how to link X11-Basic Object codes (produced by xbc)
   with your c-Program                        (c) Markus Hoffmann 2004   */

/* Example Program how to use the x11basic-Library
   with your c-Program                        (c) Markus Hoffmann 2004   */


/* You will have to compile this (c-demo2.c) and link it with the 
   x11basic shared library and with the object produced by xbc out of library.bas

xbc -l -virtualm library.bas
gcc -DNOMAIN -c library.c 

gcc  -o testme -L/usr/X11R6/lib -lx11basic -ldl -lm 
    -lreadline -lasound -lX11 c-demo2.c library.o

*/

#include <x11basic/xb2csol.h>


/* These are the declarations for all X11-Basic Procedures and Funcitons. 
   Naming is proc_<X11Basic Name uppercase>  */

extern void proc_PA();
extern void proc_B();
extern void proc_C();
extern void proc_D();
extern void proc_GREETING$();

extern void lib_library_init();

/* Variables */
/* These are the declarations for all X11-Basic (global) Variables. 
   Naming is VAR<typ>_<X11Basic Name uppercase>  
   typ can be f = float, i=int, s=string, a=array */
   
extern double VARf_X;  
extern double VARf_Y;  

/* Here your c program starts */

int main(int anzahl, char *argumente[]) {
  double ret;
  STRING str;
  int i;
  MAIN_INIT;

  /* Initialize Variables used by the main program */
  double VARf_MX;  
  double VARf_MY;  

  lib_library_init();  /* Initialize variables used by the library. 
                          The naming is: 
			  lib_<part of the original .bas filename>_init(); */
  
  /* Initialize Variables used by the main program */


  add_variable("MX",FLOATTYP,0,V_STATIC,(char *)&VARf_MX);
  add_variable("MY",FLOATTYP,0,V_STATIC,(char *)&VARf_MY);



  /* Here your code can follow */

  /* ... */
 
  /* ... */
  
  /* If you like, you can use single x11basic-commands: */

  kommando("PBOX 10,10,100,100");/* This is for single command execution: */
  kommando("COLOR GET_COLOR(65535,0,0)");
  for(i=0;i<256;i++) {
    VARf_MX=i;
    VARf_MY=150+100*sin((double)i/10);
    kommando("PLOT MX,MY");
  }

  kommando("GPRINT \"Press any key...\"");
  kommando("SHOWPAGE");
  kommando("KEYEVENT");
  kommando("MOUSE MX,MY");  /*You can also use variables*/
  /* ... */
  printf("Variable content: mx=%g, my=%g\n",VARf_MX,VARf_MY);

VARf_X=4711;

  /* This is how you can execute a X11-Basic Function generated by xbc. 
   if you expect an integer as return from the function use callifunc() instead, 
   for a STRING use callsfunc() and for ARRAY use callafunc() */
   
  callfunc(&opstack,proc_PA,"");
  callfunc(&opstack,proc_B,"");
  callfunc(&opstack,proc_C,"ff",3.0,4.0);
  ret=callfunc(&opstack,proc_D,"ff",1.1,2.2);
  printf("Returnvalue from function D was: %g\n",ret);
  printf("Variable content: x=%g, y=%g\n",VARf_X,VARf_Y);
  str=callsfunc(&opstack,proc_GREETING$,"i",815);
  printf("Return String from function GREETING$ was: <%s> len=%d\n",str.pointer,str.len);
}
