/* errortxt.c  (c) Markus Hoffmann   */

/* This file is part of X11BASIC, the basic interpreter for Unix/X
 * ============================================================
 * X11BASIC is free software and comes with NO WARRANTY - read the file
 * COPYING for details
 */
#include "options.h"

const char *errortxt[] = { 
#ifdef GERMAN
/*   0*/  "Division durch Null",
/*   1*/  "Überlauf",
/*   2*/  "Zahl nicht Integer -2147483648 .. 2147483647",
/*   3*/  "Zahl nicht Byte 0 .. 255",
/*   4*/  "Zahl nicht Wort -32768 .. 32767",
/*   5*/  "Quadratwurzel nur für positive Zahlen",
/*   6*/  "Logarithmen nur für Zahlen größer Null",
/*   7*/  "Unbekannter Fehler",
/*   8*/  "Speicher voll",
/*   9*/  "Funktion oder Befehl noch nicht möglich %s",
/*  10*/  "String zu lang",
/*  11*/  "Fehler #11",
/*  12*/  "Programm zu lang Speicher voll NEW",
/*  13*/  "Fehler #13",
/*  14*/  "Feld %s zweimal dimensioniert",
/*  15*/  "Feld nicht dimensioniert: %s()",
#else
/*   0*/  "Divide by zero",
/*   1*/  "Overflow",
/*   2*/  "Value not integer -2147483648 .. 2147483647",
/*   3*/  "Value not byte 0 .. 255",
/*   4*/  "Value not short -32768 .. 32767",
/*   5*/  "Square root: only positive numbers",
/*   6*/  "Logarithmen nur für Zahlen größer Null",
/*   7*/  "Unknown Error %s",
/*   8*/  "Out of Memory",
/*   9*/  "Function or command %s not yet implemented",
/*  10*/  "String too long",
/*  11*/  "Error #11",
/*  12*/  "Program too long, buffer size exeeded --> NEW",
/*  13*/  "Error #13",
/*  14*/  "Array %s() already dimensioned",
/*  15*/  "Array %s() not dimensioned",
#endif
#ifdef GERMAN
/*  16*/  "Feldindex zu groß",
/*  17*/  "Dim zu groß",
/*  18*/  "Falsche Anzahl Indizes",
/*  19*/  "Procedure %s nicht gefunden",
/*  20*/  "Label %s nicht gefunden",
/*  21*/  "Bei Open nur erlaubt: \"I\"nput  \"O\"utput \"A\"ppend \"U\"pdate",
/*  22*/  "File schon geöffnet",
/*  23*/  "File # falsch",
/*  24*/  "File nicht geöffnet",
/*  25*/  "Falsche Eingabe, keine Zahl",
/*  26*/  "Fileende erreicht EOF",
/*  27*/  "Zu viele Punkte für Polyline/Polyfill",
/*  28*/  "Feld muss eindimensional sein",
/*  29*/  "Fehler #29",
/*  30*/  "Merge - Kein ASCII-File",
/*  31*/  "Merge - Zeile zu lang - Abbruch",
/*  32*/  "==> Syntax nicht korrekt %s",
#else
/*  16*/  "Field index too large",
/*  17*/  "Dim too large",
/*  18*/  "Wrong number of indicies",
/*  19*/  "Procedure %s not found",
/*  20*/  "Label %s not found",
/*  21*/  "Open only \"I\"nput  \"O\"utput \"A\"ppend \"U\"pdate",
/*  22*/  "File already opened",
/*  23*/  "Wrong file #",
/*  24*/  "File not opened",
/*  25*/  "Wrong input, no number",
/*  26*/  "EOF - reached end of file",
/*  27*/  "Too many points for Polyline/Polyfill",
/*  28*/  "Array must be one dimensional",
/*  29*/  "Error #29",
/*  30*/  "Merge - no ASCII file",
/*  31*/  "Merge - line too long - CANCEL",
/*  32*/  "==> Syntax error %s",
#endif
/*  33*/  "Marke nicht definiert",
/*  34*/  "Zu wenig Data",
/*  35*/  "Data nicht numerisch",
/*  36*/  "Programmstruktur Fehlerhaft %s",
/*  37*/  "Diskette voll",
/*  38*/  "Befehl %s im Direktmodus nicht möglich",
/*  39*/  "Programmfehler Kein Gosub möglich",
/*  40*/  "Clear nicht möglich in For-Next-Schleifen oder Proceduren",
/*  41*/  "Cont nicht möglich",
/*  42*/  "Zu wenig Parameter %s",
/*  43*/  "Ausdruck zu komplex",
/*  44*/  "Funktion %s nicht definiert",
/*  45*/  "Zu viele Parameter",
/*  46*/  "Parameter %s falsch, keine Zahl",
/*  47*/  "Parameter %s falsch, kein String",
/*  48*/  "Open \"R\" - Satzlänge falsch",

/* 1*/  "Zu viele \"R\"-Files (max. 31)",
/* 2*/  "Kein \"R\"-File",
/* 3*/  "Parser: Syntax Error <%s>",
/* 4*/  "Fields größer als Satzlänge",
/* 5*/  " Fehler 53",
/* 6*/  "GET/PUT Field-String Länge falsch",
/* 7*/  "GET/PUT Satznummer falsch",
/* 56*/  "Falsche Anzahl Parameter",
/* 57*/  "Variable %s noch nicht initialisiert",
/* 58*/  "Variable %s ist vom falschen Typ",
/* 59*/  "Fehler 59",
/* 60*/  "Sprite-String-Länge falsch",
/* =*/  "Fehler bei RESERVE",
/* >*/  "Menu falsch",
/* ?*/  "Reserve falsch",

/* 64*/  "Pointer falsch",
/* A*/  "Feldgröße < 256",
/* B*/  "Kein VAR-Array",
/* C*/  "ASIN/ACOS falsch",
/*  68*/  "Falsche VAR-Type",
/*  69*/  "ENDFUNC ohne RETURN",
/*  70*/  "Unbekannter Fehler 70",
/*  71*/  "Index zu groß",
/* H*/  " Fehler 72",
/* I*/  " Fehler 73",
/* J*/  " Fehler 74",
/* K*/  " Fehler 75",
/* L*/  " Fehler 76",
/* M*/  " Fehler 77",
/* N*/  " Fehler 78",
/* O*/  " Fehler 79",

/* P*/  "Matrizenoperationen nur für ein- oder zweidimensionale Felder",
/* Q*/  "Matrizen haben nicht die gleiche Ordnung",
/* R*/  "Vektorprodukt nicht definiert",
/* S*/  "Matrizenprodukt nicht definiert",
/* T*/  "Scalarprodukt nicht definiert",
/* U*/  "Transposition nur für zweidimensionale Matrizen",
/* V*/  "Matrix nicht quadratisch",
/* W*/  "Transposition nicht definiert",
/* X*/  "FACT/COMBIN/VARIAT nicht definiert",
/*  89*/  " Fehler 89",
/*  90*/  "Fehler bei Local",
/*  91*/  "Fehler bei For",
/*  92*/  "Resume (next) nicht möglich   Fatal, For oder Local",
/*  93*/  "Stapel-Fehler",
/*  94*/  " Fehler 94",
/* _*/  " Fehler 95",

/*  `*/  "Error 96",
/*  a*/  "Error 97",
/*  98*/  "Error 98",
/*  99*/  "Error 99",
/* 100*/  "X11BASIC Version 1.06  Copyright (c)1998-2002 Markus Hoffmann",
/* e*/  "** 1 - Segmentation fault : Speicherschutzverletzung",
/* f*/  "** 2 - Bus Error Peek/Poke falsch?",
/* g*/  "** 3 - Adress error Ungerade Wort-Adresse! Dpoke/Dpeek, Lpoke/Lpeek?",
/* h*/  "** 4 - Illegal Instruction : ungültiger Maschinenbefehl",
/* i*/  "** 5 - Divide by Zero : Division durch Null",
/* j*/  "** 6 - CHK exeption : CHK-Befehl",
/* k*/  "** 7 - TRAPV exeption : TRAPV-Befehl",
/* l*/  "** 8 - Privilege Violation : Privilegverletzung",
/* m*/  "** 9 - Trace exeption : Trace ohne Monitor",
/* n*/  "** 10 - Broken pipe : Ausgabeweitergabe abgebrochen",
/* o*/  "Error 111",

/* p*/  " Fehler 112",
/* q*/  " Fehler 113",
/* r*/  " Fehler 114",
/* s*/  " Fehler 115",
/* t*/  " Fehler 116",
/* u*/  " Fehler 117",
/* v*/  " Fehler 118",
/* w*/  " Fehler 119",
/* x*/  " Fehler 120",
/* y*/  " Fehler 121",
/* z*/  " Fehler 122",
/* {*/  " Fehler 123",
/*  */  " Fehler 124",
/* }*/  " Fehler 125",
/* ~*/  " Fehler 126",
/* 127*/" Fehler 127",

/* €*/  " Fehler -128",
/* */  " Fehler -127",
/* ‚*/  " Fehler -126",
/* -125*/  "* Number of hash collisons exceeds maximum generation counter value.",
/* -124*/  "* Wrong medium type : Andere Diskette einlegen",
/* -123*/  "* No medium found : Bitte Disk einlegen",
/* -122*/  "* Quota exceeded",
/* -121*/  "* Remote I/O error",
/* -120*/  "* Is a named type file",
/* -119*/  "* No XENIX semaphores available",
/* -118*/  "* Not a XENIX named type file",
/* -117*/  "* Structure needs cleaning",
/* -116*/  "* Stale NFS file handle",
/* -115*/  "* Operation now in progress",
/* -114*/  "* Operation already in progress",
/* -113*/  "* No route to host",
/* -112*/  "* Host is down",
/* -111*/  "* Connection refused : Verbindungsaufbau verweigert",
/* -110*/  "* Connection timed out : Zeitüberschreitung bei Verbindung",
/* -109*/  "* Too many references: cannot splice",
/* -108*/  "* Cannot send after transport endpoint shutdown",
/* -107*/  "* Transport endpoint is not connected : Keine Verbindung, Verbindung unterbrochen ?",
/* -106*/  "* Transport endpoint is already connected : Verbindung schon geöffnet ",
/* -105*/  "* No buffer space available : Speicher voll",
/* -104*/  "* Connection reset by peer",
/* -103*/  "* Software caused connection abort : Verbindungsabbruch durch Anwender",
/* -102*/  "* Network dropped connection because of reset",
/* -101*/  "* Network is unreachable",
/* -100*/  "* Network is down",
/* -99*/  "* Cannot assign requested address %s : Verbindungsaufbau nicht möglich",
/* -98*/  "* Address %s already in use : Besetzt, Verbindung nicht möglich",
/* -97*/  "* Address family not supported by protocol",
/* -96*/  "* Protocol family not supported",
/* -95*/  "* Operation not supported on transport endpoint",
/* -94*/  "* Socket type not supported",
/* -93*/  "* Protocol not supported",
/* -92*/  "* Protocol not available",
/* -91*/  "* Protocol wrong type for socket",
/* -90*/  "* Message too long",
/* -89*/  "* Destination address required",
/* -88*/  "* Socket operation on non-socket : Operation nur mit Sockets erlaubt",
/* -87*/  "* Too many users",
/* -86*/  "* Streams pipe error",
/* -85*/  "* Interrupted system call should be restarted",
/* -84*/  "* Illegal byte sequence",
/* -83*/  "* Cannot exec a shared library directly",
/* -82*/  "* Attempting to link in too many shared libraries",
/* -81*/  "* .lib section in a.out corrupted",
/* -80*/  "* Accessing a corrupted shared library",
/* -79*/  "* Can not access a needed shared library",
/* -78*/  "* Remote address changed",
/* -77*/  "* File descriptor in bad state",
/* -76*/  "* Name not unique on network",
/* -75*/  "* Value too large for defined data type",
/* -74*/  "* Not a data message",
/* -73*/  "* RFS specific error",
/* -72*/  "* Try again : Operation zur Zeit nicht möglich",
/* -71*/  "* Too many symbolic links encountered",
/* -70*/  "* File name too long : Dateiname zu lang",
/* -69*/  "* Resource deadlock would occur",
/* -68*/  "* Advertise error",
/* -67*/  "* Speicherblockfehler",
/* -66*/  "* Kein Binärprogramm",
/* -67*/  "* Link has been severed",
/* -66*/  "* Object is remote",
/* -63*/  "* Math result not representable",
/* -62*/  "* Math arg out of domain of func",
/* -61*/  "* Cross-device link",
/* -60*/  "* Device not a stream",
/* -59*/  "* Mount device busy",
/* -58*/  "* Block device required",
/* -57*/  "* Bad address",
/* -56*/  "* No more processes",
/* -55*/  "* No children",
/* -54*/  "* Exchange full",
/* -53*/  "* Interrupted system call",
/* -52*/  "* Invalid exchange",
/* -51*/  "* Permission denied, you must be super-user",
/* -50*/  "* Operation auf diesem Kanal nicht (mehr) möglich",
/* -49*/  "* Keine weiteren Dateien",
/* -48*/  "* Link number out of range",
/* -47*/  "* Level 3 reset",
/* -46*/  "* Ungültige Laufwerksbezeichnung",
/* -45*/  "* Level 2 not synchronized",
/* -44*/  "* Channel number out of range",
/* -43*/  "* Identifier removed",
/* -42*/  "* No message of desired type",
/* -41*/  "* Operation %s would block",
/* -40*/  "* Ungültige Speicherblockadresse",
/* -39*/  "* Directory %s not empty : Das Verzeichnis ist nicht leer",
/* -38*/  "* Function %s not implemented : Unbekannter Befehl",
/* -37*/  "* Ungültiges Handle %s",
/* -36*/  "* Zugriff nicht möglich",
/* -35*/  "* Zu viele Dateien offen",
/* -34*/  "* Pfadname nicht gefunden",
/* -33*/  "* Datei nicht gefunden",
/* -32*/  "* Broken pipe : Verbindung wurde unterbrochen",
/* -31*/  "* Too many links : Zu viele Links",
/* -30*/  "* Read-Only File-System : File-System ist Schreibgeschützt",
/* -29*/  "* Illegal seek : Seek falsch",
/* -28*/  "* No space left on device %s : File-System ist voll",
/* -27*/  "* File too large : File %s ist zu gross für diese Operation",
/* -26*/  "* Text file %s busy",
/* -25*/  "* %s Not a typewriter",
/* -24*/  "* Too many open files",
/* -23*/  "* File table overflow : Zur Zeit sind keine weiteren offenen Files möglich",
/* -22*/  "* Invalid argument %s",
/* -21*/  "* %s Is a directory",
/* -20*/  "* %s Not a directory",
/* -19*/  "* No such device %s",
/* -18*/  "* Cross-device link",
/* -17*/  "* File exists",
/* -16*/  "* Bad Sektor (Verify)",
/* -15*/  "* Unbekanntes Gerät",
/* -14*/  "* Diskette wurde gewechselt",
/* -13*/  "* Permission denied : Die Erlaubnis wurde verweigert",
/* -12*/  "* Not enough core : Speicher voll",
/* -11*/  "* Lesefehler",
/* -10*/  "* Schreibfehler",
/*  -9*/  "* Kein Papier",
/*  -8*/  "* Sektor nicht gefunden",
/*  -7*/  "* Arg list too long : Zu viele Parameter",
/*  -6*/  "* Seek Error Spur nicht gefunden",
/*  -5*/  "* Bad Request Ungültiger Befehl",
/*  -4*/  "* CRC Fehler Disk-Prüfsumme falsch",
/*  -3*/  "* No such process",
/*  -2*/  "* Timeout",
/*  -1*/  "* IO-Error : Allgemeiner IO-Fehler %s"
};

char *error_text(unsigned char err, char *bem) {
  static char errbuffer[128];
  sprintf(errbuffer,errortxt[err],bem );
  return(errbuffer);
}

